[package]
name = "gork"
version = "0.1.0"
edition = "2024"

[dependencies]
gemini-rs = "2.0.0"
serenity = { version = "0.12.4", features = ["cache", "temp_cache"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.142"
